algoritmo "semnome"
// Função :
// Autor :
// Data : 15/04/2015
// Seção de Declarações 
var
num: real
inicio
      num <- 5.68
      escreval (num:1:1)
      //arredondamento (num:a:b), para a= casas decimais antes da vírgula
      // e b= casas depois da vírgula
      escreval (int(num))
      //truncamento
      escreval ((num)- int(num))// parte fracionada menos a parte inteira
fimalgoritmo
