algoritmo "semnome"
// Função :
// Autor :
// Data : 14/04/2015
// Seção de Declarações 
var
   n: inteiro
   i: inteiro
inicio
// Seção de Comandos
   escreva ("Digite um número para listagem: ")
   leia (n)
   se n>100 entao
      escreval ("Valor não permitido")
      senao
           para i de 1 ate n faca
                escreva (i)
           fimpara
   fimse
fimalgoritmo
