algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2015
// Seção de Declarações 
var
j: inteiro
y: inteiro
soma: inteiro
inicio
// ":3" significa que eu quero que o numero ou o texto "pule" 3 caracteres
      escreval("insira um número:")
      leia (y)
      para j de 1 ate y faca
           escreva (j:3)
           soma <- soma + j
                escreval (soma:3)
      fimpara
fimalgoritmo
