algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2015
// Seção de Declarações 
var
// Exemplo 1
numeros: vetor [1..10] de inteiro
i: inteiro
inicio
      para i de 1 ate 10 faca
           escreva ("Digite um número ")
           leia (numeros[i])
      fimpara
      escreva ("Números na ordem correta: ")
      para i de 1 ate 10 faca
           escreva (numeros [i])
      fimpara
fimalgoritmo
