algoritmo "semnome"
// Função :
// Autor :
// Data : 29/03/2015
// Seção de Declarações 
var
j,i: inteiro
inicio
// Seção de Comandos
// se ( j mod 2 = 0), então significa que ele irá selecionar os numeros pares, logo j é par
// se ( j mod 2 <> 0), então significa que ele irá selecionar os numeros impares, logo j é impar
para j de 1 ate 10  faca
     se (j % 2 <> 0) entao
        escreval(j:3)
     fimse
     
fimpara
fimalgoritmo
