algoritmo "semnome"
// Função :
// Autor :
// Data : 19/03/2015
// Seção de Declarações 
var
   nota: real
inicio
// Seção de Comandos
   escreva ("Insira um número:")
   leia (nota)
        se (nota >=10) entao
           escreval ("Verdadeiro, este número é maior que 10")
           senao
                se (nota <10) entao
                   escreval ("Falso, este número não é maior que 10")
                fimse
        fimse
fimalgoritmo
