algoritmo "semnome"
// Função :
// Autor :
// Data : 01/04/2015
// Seção de Declarações 
var
numero: vetor [1..10] de inteiro
i: inteiro
soma: inteiro
inicio
      para i de 1 ate 10 faca
            escreval ("Insira um valor")
            leia (numero[i])
      fimpara
      para i de 1 ate 10 faca
           soma <- soma + numero[i]
           escreval (soma)
      fimpara

fimalgoritmo
