algoritmo "Questão2"
// Função :
// Autor : RUAN LUIZ ALVES DA SILVA
// Data : 16/04/2015
// Seção de Declarações 
var
   senha: caractere
inicio
// Seção de Comandos
   escreval ("Digite sua senha para logar no sistema:")
   leia (senha)
        enquanto senha<> "poderoso" faca
                 escreval ("Digite a senha correta")
                 leia (senha)
        fimenquanto
   escreval ("Acesso concedido!")
fimalgoritmo
