algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2015
// Seção de Declarações 
var
x,y,z:inteiro
soma: inteiro
inicio
      escreva ("Digite um número: ")
      leia (x)
      escreva ("Digite outro número: ")
      leia (y)
      escreva ("Digite mais outro número: ")
      leia (z)
      soma <- x+y+z
      escreval
      escreval (" A soma destes números é igual a: ", soma)
fimalgoritmo
