algoritmo "semnome"
// Função :
// Autor :
// Data : 05/04/2015
// Seção de Declarações 
var
a, b, per, area: inteiro
inicio
      escreval ("Digite o lado maior do retângulo: ")
      leia (a)
      escreval ("Digite o lado menor do retângulo: ")
      leia (b)
      per <- 2*a+2*b
      area <- a*b
      escreval
      escreval ("Área: ", area, "; Perímetro: ", per)
fimalgoritmo
